services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -f Dockerfile -t cicd-pipeline:$TAG .
  - docker push cicd-pipeline:$TAG
#  - sh .travis/deploy_dockerhub.sh