services:
  - docker

language: python

script:
  - python -m pytest -v

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -f Dockerfile -t cicd-pipeline:$TAG .
  - docker push cicd-pipeline:$TAG
#  - sh .travis/deploy_dockerhub.sh